from abc import ABC, abstractmethod


class BaseStorage(ABC):
    """Abstract base for file-based content storage."""

    # Projects
    @abstractmethod
    async def list_projects(self, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def get_project(self, project_id: str, user_id: str) -> dict | None: ...
    @abstractmethod
    async def create_project(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_project(self, project_id: str, user_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete_project(self, project_id: str, user_id: str) -> bool: ...

    # Documents
    @abstractmethod
    async def list_documents(self, project_id: str, user_id: str, parent_id: str | None = None) -> list[dict]: ...
    @abstractmethod
    async def get_document(self, document_id: str, user_id: str) -> dict | None: ...
    @abstractmethod
    async def create_document(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_document(self, document_id: str, user_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete_document(self, document_id: str, user_id: str) -> bool: ...
    @abstractmethod
    async def reorder_documents(self, project_id: str, user_id: str, document_ids: list[str]) -> bool: ...

    # Characters
    @abstractmethod
    async def list_characters(self, project_id: str, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def get_character(self, character_id: str, user_id: str) -> dict | None: ...
    @abstractmethod
    async def create_character(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_character(self, character_id: str, user_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete_character(self, character_id: str, user_id: str) -> bool: ...
    @abstractmethod
    async def reorder_characters(self, project_id: str, user_id: str, item_ids: list[str]) -> bool: ...
    @abstractmethod
    async def list_character_history(self, character_id: str, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def add_character_history(self, character_id: str, user_id: str, data: dict) -> dict: ...

    # Story Bible
    @abstractmethod
    async def list_story_bible(self, project_id: str, user_id: str, category: str | None = None) -> list[dict]: ...
    @abstractmethod
    async def create_story_bible(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_story_bible(self, entry_id: str, user_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete_story_bible(self, entry_id: str, user_id: str) -> bool: ...
    @abstractmethod
    async def reorder_story_bible(self, project_id: str, user_id: str, item_ids: list[str]) -> bool: ...

    # Story Engine
    @abstractmethod
    async def list_outlines(self, project_id: str, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def create_outline(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_outline(self, outline_id: str, user_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete_outline(self, outline_id: str, user_id: str) -> bool: ...
    @abstractmethod
    async def reorder_outlines(self, project_id: str, user_id: str, item_ids: list[str]) -> bool: ...
    @abstractmethod
    async def create_beat(self, outline_id: str, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_beat(self, beat_id: str, user_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete_beat(self, beat_id: str, user_id: str) -> bool: ...

    # Style Guide
    @abstractmethod
    async def list_style_guide(self, project_id: str, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def create_style_guide(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_style_guide(self, entry_id: str, user_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete_style_guide(self, entry_id: str, user_id: str) -> bool: ...
    @abstractmethod
    async def reorder_style_guide(self, project_id: str, user_id: str, item_ids: list[str]) -> bool: ...

    # Canvas
    @abstractmethod
    async def list_canvas_nodes(self, project_id: str, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def create_canvas_node(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_canvas_node(self, node_id: str, user_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete_canvas_node(self, node_id: str, user_id: str) -> bool: ...
    @abstractmethod
    async def list_canvas_edges(self, project_id: str, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def create_canvas_edge(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def delete_canvas_edge(self, edge_id: str, user_id: str) -> bool: ...

    # Skills
    @abstractmethod
    async def list_skills(self, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def get_skill(self, skill_id: str, user_id: str) -> dict | None: ...
    @abstractmethod
    async def create_skill(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_skill(self, skill_id: str, user_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete_skill(self, skill_id: str, user_id: str) -> bool: ...
